'use strict';
// ---------------------------------------------------------------------------
// Chapter Two maps: the continent of Ashkar (Dominion of Flame and Ash).
// Adds a second world map (MAPS.ashkar) and its towns and dungeons.
// Story events for these maps live in events2.js.
// ---------------------------------------------------------------------------
MAPS.ashkar = {
  id: 'ashkar', name: 'Ashkar', world: true, theme: 'ashworld', music: 'ashkar',
  rows: [
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~a~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~a~~~~~~~~ajjjjjjja~~~~~~~",
    "~~~~~~~~~~~~~~~~~~ooooooooaaaaaaajjjaaaaajjja~~~~~",
    "~~~~~~~~~~~~~~~oooooZooooooaaaaajjaaaaaaaaajja~~~~",
    "~~~~~~~~~~~~aaaoooooooooooaaaaajjaaaaaaaaaaajja~~~",
    "~~~~~~~~~~~aaaaaoooooooooaaaaaajaaaaaaaaaaaaajaa~~",
    "~~~~~~~~~aaaaaaaaaaaoaaaaaaaaaakaaaaaaNaaaaaajaa~~",
    "~~~~~~~~^^^^^^^^^^^n^^^^^^^^^^^jaaaaaaaaaaaaajaa~~",
    "~~~~~~~^^^^^^^^^^^^n^^^^^^^^^^^jjaaaaaaaaaaajjaaa~",
    "~~~~~~aaaaaaaaaadaaaaaaaaaaaaaaajjaaaaaaaaajjaaa~~",
    "~~~~~aaaaaaaadddddddaaaaaaaaaaaaajjjaaaaajjjaaaa~~",
    "~~~~~aaaaaaaddddddddUaaaaaaaaaaaaaajjjjjjjaaaaaa~~",
    "~~~~aaaaaaaaadddddddaaaaaaaaaaaaaaaaaaaaaaaaaaa~~~",
    "~~~~aaaaaaaaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa~~~",
    "~~~~aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa~~~",
    "~~~~jjjjjjjjjjjjjjjjmjjjjjjjjjjjjjjjjjjjjjjjjjj~~~",
    "~~~jjjjjjjjjjjjjjjjjmjjjjjjjjjjjjjjjjjjjjjjjjjjj~~",
    "~~~~aaaaaadaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa~~~",
    "~~~~aaaadddddaaaaaaajaaaaaaaaaaaaaaaaaaaaaaaaaa~~~",
    "~~~~aaadddddddaaaaaaajaaaaaaaaoaaaaaXaaaaaaaaaa~~~",
    "~~~~aadddddddddaaaaajaaaaaaoooooooaaaaoaaaaaaaa~~~",
    "~~~~aaadddddddaaaaaaajaaaaoooooooooaoooooaaaaa~~~~",
    "~~~aaaaaddddWaaaaaaaaaaaaoooooooooooooooooaaaa~~~~",
    "~~~~aaaaaadaaaaaaaaaajaaaaoooooooooaoooooaaaa~~~~~",
    "~~~~aaaaaaaaaaaaaaaajaaaaaaoooooooaaaaoaaaaa~~~~~~",
    "~~~~aaaaaaaaaaaaaaaaajaaaaaaaaoaaaaaaaaaaaa~~~~~~~",
    "~~~~~aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa~~~~~~~~",
    "~~~~~~aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa~~~~~~~~~~",
    "~~~~~~~~aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa~~~~~~~~~~~",
    "~~~~~~~~~~~~a~~aaaaaaaaaQaaaaaaaaaaa~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~aaaaaaaaaaaaaaa~~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~a~~~~~~~~~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
  ],
  // gate tiles: [flag that opens it, tile when open, tile when closed]
  gates: { m: ['gunworks', 'B', 'j'], n: ['draumond', 'a', '^'], k: ['ferryman', 'B', 'j'] },
  places: {
    '24,31': { map: 'emberport', at: [14, 2, 'down'] },
    '12,24': { map: 'charnoch' },
    '36,21': { map: 'kharakyr' },
    '20,13': { map: 'draumond' },
    '20,5': { map: 'terminus1' },
    '38,8': { map: 'cinders' },
  },
  zone(x, y, t) {
    if (t === '~') return 'sea';
    if (x >= 32 && x <= 44 && y >= 4 && y <= 12) return 'caldera';
    if (y <= 10) return 'grave';
    if (y >= 26 && Math.abs(x - 24) < 10) return 'ashport';
    return 'ashplains';
  },
  bg(x, y, t) {
    if (x >= 32 && x <= 44 && y >= 4 && y <= 12) return 'caldera';
    if (y <= 10) return 'volcano';
    if (t === 'o') return 'lava';
    return 'ashplains';
  },
};

Object.assign(MAPS, {
  // =========================================================================
  emberport: {
    name: 'Emberport', theme: 'emberport', music: 'emberport', under: 'g', exitArt: 'path', worldId: 'ashkar', back: [24, 30], start: [14, 2, 'down'],
    rows: [
      "##############XX##############",
      "#ggggggggggggg,,ggggggggggggg#",
      "#gRRRRRgRRRRRg,,1gRRRRRRRRRRg#",
      "#gRRRRRgRRRRRg,,ggRRRRRRRRRRg#",
      "#gbbWbbgbbAbbg,,ggbbIbbbbNbbg#",
      "#ggggggggggggg,,ggggggggggggg#",
      "#ggggggggggggg,,ggggggggggggg#",
      "#ggggggggggggg,,gggggggggggQg#",
      "#g,,,,,,,,,,,,,,,,,,,,,,,,,,g#",
      "#gggg2gggggggg,,gggg4gggggggg#",
      "#gRRRRRggggggg,,gggggggRRRRRg#",
      "#gRRRRRgeaeggg,,gggLgggRRRRRg#",
      "#gbbHbbggggg3g,,g6gggggbbbbbg#",
      "#ggggggggggggg,,ggggggggggggg#",
      "#g,,,,,,,,,,,,,,,,,,,,,,,,,,g#",
      "#ggg8ggegggggg,,ggggggegg5ggg#",
      "#,,,,,,,,,,,,,,,,,,,,,,,,,,,,#",
      "#~~~~~~~~~~~====7=~~~~~~~~~~~#",
      "#~~~~~~~~~~~======~~~~~~~~~~~#",
      "##############################",
    ],
    shops: 'emberport', underAt: { '7': '=' },
    chests: { Q: { id: 'c2_ember1', item: 'hiether' } },
    npcs: {
      1: { look: 'hobgob', name: 'Gate Captain Hrask', talk: [async () => emberGateEvent()] },
      2: { look: 'orc', name: 'Dockworker', act: 'hammer', talk: [() => "Might makes right, the Edicts say. I'm very mighty. My back still hurts. Explain THAT, Malakar."] },
      3: { look: 'kobold', move: 'wander', talk: [() => "Is the dragon lady a GOD? No? Then why does she look so smug?"] },
      4: { look: 'zealot2', name: 'Phoenix Preacher', talk: [() => "The Tenth Flame rose from NOTHING! A little bird no one feared! If he can become a god, so can you! ...Donations welcome."] },
      5: { look: 'dwarf', name: 'Smith', act: 'hammer', talk: [() => "Want real steel? Kharak Yr, east across the ash. The goblins there make guns now. Guns! In MY lifetime."] },
      6: { look: 'hobgob', name: 'Legionnaire', talk: [async () => lunaEmberport()] },
      7: { look: 'sailor', name: 'Wren Crew', talk: [async () => sailToAurelion()] },
      8: { look: 'grimpriest', name: 'Grimnarite', act: 'pray', talk: [() => "Every soul that passes is written in the Book of the Dead at Draumond's Gate. North, past the lava. The Ash-Father forgets no one."] },
    },
    signs: { '9,11': async () => zarielShrine() },
    steps: { '14,1': () => !flag('emberGate') && emberGateEvent(), '15,1': () => !flag('emberGate') && emberGateEvent() },
  },
  // =========================================================================
  charnoch: {
    name: 'Charnoch, the Burning Village', theme: 'ashen', music: 'emberport', under: 'h', exitArt: 'path', worldId: 'ashkar', back: [12, 25], start: [12, 14, 'up'], embers: () => true,
    rows: [
      "xxxxxxxxxxxxxxxxxxxxxxxxxx",
      "xhhhhhhhhhhhDDhhhhhhhhhhhx",
      "xhRRRRRhhhhhDDhhhRRRRRhhhx",
      "xhRRRRRhhhhhDDhhhRRRRRhhhx",
      "xhbbIbbhhhhhPPhhhbbNbbhhhx",
      "xhhhhhhhh1hhDDhhhhhhhhhhhx",
      "x,,,,,,,,,,,,,,,2,,,,,,,,x",
      "xhhhhhhhhhhaDDh6hhhhhhhhhx",
      "xhhhhhhhhhhhDDhhhhhhhhhhhx",
      "xhRRRRRhhhhhDDhhhhRRRRRhhx",
      "xhRRRRRhhhhhPPhhhhRRRRRhhx",
      "xhbbbbbhhh5hDDhhhhbbbbbhhx",
      "x,,,,,,,,,,,,,,,,,,,,,,,,x",
      "xhhhh3hhhhhhPPhhhhhh4hhQhx",
      "xhhhhhhhhhhhPPhhhhhhhhhhhx",
      "xxxxxxxxxxxxXXxxxxxxxxxxxx",
    ],
    shops: 'charnoch',
    chests: { Q: { id: 'c2_charnoch1', item: 'megatonic', n: 2 } },
    npcs: {
      1: { look: 'orc', name: 'Mother Coal', talk: [async () => charnochToken()] },
      2: { look: 'orc', move: 'wander', talk: [() => "A vent opened under the village. We built stilts. Now we cook on the lava. Best bread on the continent."] },
      3: { look: 'child', move: 'wander', talk: [() => "My grandpa went into the lava! On purpose! The priests say he went straight through the Final Gate. Zoom!"] },
      4: { look: 'hollowwoman', act: 'sweep', talk: [() => "Sweeping ash. Every day. It never stops falling. That's sort of comforting, isn't it?"] },
      5: { look: 'zealot2', name: 'Zealot', talk: [() => "The Throne of Cinders is where the Tenth Flame sits when he visits the world. North-east, inside the ring of lava. Nobody gets in unless he wants them to."] },
      6: { look: 'dwarf', talk: [() => "The Crimson Edict took the Gunworks at Kharak Yr last month. Hired swords. Paid in gold with a smell of night on it."] },
    },
    signs: { '11,7': () => say(null, "A tiny shrine to Grimnar where the lava cools into black glass. Villagers leave their dead's ashes here, so the Ash-Father can find them quickly.") },
  },
  // =========================================================================
  kharakyr: {
    name: 'Kharak Yr, the Cinder Forge', theme: 'forge', music: 'forge', under: 'U', exitArt: 'path', worldId: 'ashkar', back: [36, 22], start: [13, 16, 'up'],
    rows: [
      "############################",
      "#UUUUUUUUUUUUUUUUUUUUUUUUUU#",
      "#URRRRRURRRRRUURRRRRURRRRRU#",
      "#URRRRRURRRRRUURRRRRURRRRRU#",
      "#UbbWbbUbbAbbUUbbIbbUbbNbbU#",
      "#UUUUUUUUUUUUUUUUUUUUUUUUUU#",
      "#,,,,,,,,,,,,,,,,,,,,,,,,,,#",
      "#UUUU1UUUUUUUUUUUUU2UUUUUUU#",
      "#UUUUUUUUU#*####*#UUUUUUUUU#",
      "#URRRRRUUU########UUURRRRRR#",
      "#URRRRRUUU########UUURRRRRR#",
      "#UbbHbbUUU########UUUbbbbbb#",
      "#UUUUUUUUU###++###UUUUUUUUU#",
      "#UUUUUUUUUUU3UUUUU6UUUUULUU#",
      "#,,,,,,,,,,,,,,,,,,,,,,,,,,#",
      "#UU5UUUUUUUUU,,UUUUUUUUU4UU#",
      "#UUUUUUUUUUUU,,UUUUUUUUUUUU#",
      "#############XX#############",
    ],
    shops: 'kharakyr',
    npcs: {
      1: { look: 'dwarf', name: 'Gunsmith', act: 'hammer', talk: [() => "The Crimson Edict took our Gunworks. They're building something big in there. Bigger than 'Grimnar's Voice', and that's our biggest cannon."] },
      2: { look: 'kobold', move: 'wander', talk: [() => "Boom boom? No boom. They took all the boom. Sad kobold."] },
      3: { look: 'hobgob', name: 'Edict Guard', talk: [() => flag('gunworks') ? "...I don't work here anymore." : "The Gunworks are closed. Crimson Edict business. Unless you've got a Foundry Pass, walk away."] },
      4: { look: 'brakka', name: 'Brakka', show: () => !member('brakka') && !flag('brakkaGone'), talk: [async () => brakkaEvent()] },
      5: { look: 'orc', talk: [() => "Draumond's Gate is north, over the lava. The Edict raised the bridge so nobody could warn the priests. Warn them about what? Nobody says."] },
      6: { look: 'kobold', act: 'dance', talk: [() => "I dance when I'm nervous! I'm ALWAYS nervous!"] },
    },
    steps: { '13,12': () => enterGunworks(), '14,12': () => enterGunworks() },
  },
  gunworks1: {
    name: 'The Gunworks', theme: 'forge', music: 'forge', under: '.', exitArt: 'floor', back: { map: 'kharakyr', x: 13, y: 13, dir: 'down' }, start: [6, 14, 'up'], enc: 'forge', encRate: 0.065, bg: 'forge',
    rows: [
      "########################",
      "#Q..DDD....#......>....#",
      "#...DDD.PPP#..DD.......#",
      "#..........#..DD..###..#",
      "####.#######......#V#..#",
      "#....#.....PPPP...#.#..#",
      "#.DD.#..DD.#..#........#",
      "#.DD....DD.#..####.#####",
      "#......PP..#.....#.....#",
      "######.#####.DD..#..DD.#",
      "#......#.....DD..#..DD.#",
      "#.PPP..#..L......P.....#",
      "#.DDD..####.####.#####.#",
      "#.DDD........C.#.......#",
      "#..........#...#...DD..#",
      "######XX################",
    ],
    warps: { '>': { map: 'gunworks2', at: '<' } },
    chests: { Q: { id: 'c2_gun1a', item: 'hitonic', n: 3 }, V: { id: 'c2_gun1b', item: 'obsidianfang' }, C: { id: 'c2_gun1c', item: 'megatonic' } },
  },
  gunworks2: {
    name: 'The Gunworks - Proving Floor', theme: 'forge', music: 'forge', under: '.', exitArt: 'floor', start: [1, 11, 'right'], bg: 'forge',
    rows: [
      "######################",
      "#*.......*..*.......*#",
      "#....DD........DD....#",
      "#....DD...1....DD....#",
      "#....................#",
      "#..PP............PP..#",
      "#..PP....GGGG....PP..#",
      "#........GGGG........#",
      "#.DD..............DD.#",
      "#.DD.......L......DD.#",
      "#....................#",
      "#...V............Q...#",
      "#<...................#",
      "######################",
    ],
    warps: { '<': { map: 'gunworks1', at: '>' } }, underAt: { '1': '.' },
    chests: { V: { id: 'c2_gun2a', item: 'gravestaff' }, Q: { id: 'c2_gun2b', item: 'handcannon' } },
    npcs: { 1: { enemy: 'cannongolem', scale: 0.5, name: 'Grimnar\'s Voice', show: () => !flag('gunworks'), talk: [async () => cannonEvent()] } },
    steps: { '9,5': () => !flag('gunworks') && cannonEvent(), '10,5': () => !flag('gunworks') && cannonEvent(), '11,5': () => !flag('gunworks') && cannonEvent(), '12,5': () => !flag('gunworks') && cannonEvent() },
  },
  // =========================================================================
  draumond: {
    name: 'Draumond\'s Gate', theme: 'necro', music: 'grave', under: '.', exitArt: 'path', worldId: 'ashkar', back: [20, 14], start: [13, 16, 'up'],
    rows: [
      "############################",
      "#..........######..........#",
      "#........Z.######..........#",
      "#..........##aa##.L........#",
      "#...........1,,............#",
      "#..J.J.J.....,,7....J.J.J..#",
      "#...2........,,.......3....#",
      "#..J.J.J.....,,.....J.J.J..#",
      "#.........4..,,............#",
      "#............,,............#",
      "#.RRRRR.RRRR.,,..RRRR.RRRRR#",
      "#.RRRRR.RRRR.,,..RRRR.RRRRR#",
      "#.bbAbb.bbIb.,,..bbNb.bbHbb#",
      "#............,,...5........#",
      "#,,,,,,,,,,,,,,,,,,,,,,,,,,#",
      "#.....6......,,............#",
      "#............,,............#",
      "#############XX#############",
    ],
    shops: 'draumond',
    npcs: {
      1: { look: 'grimpriest', name: 'Keeper of the Book', talk: [async () => bookOfTheDead()] },
      2: { look: 'hollowwoman', name: 'Mourner', act: 'pray', talk: [() => "My husband's name went into the Book this morning. I watched the ink dry. That's how you know they arrived."] },
      3: { look: 'grimpriest', act: 'pray', talk: [() => "The Final Gate has gone dark. The Ferryman stopped answering the bell. Something is sitting in his boat that isn't him."] },
      4: { look: 'dwarf', name: 'Gravekeeper', act: 'sweep', talk: [() => "Every grave here faces Mount Terminus. So they can see where they're going. Considerate, the dead."] },
      5: { look: 'child', move: 'wander', talk: [() => "Are you dead? You look tired enough to be dead. Mum says that's rude to ask."] },
      6: { look: 'orc', talk: [() => "The pass to Mount Terminus opens only for those the Keeper sends. Talk to him in the Hall of the Book. North end."] },
      7: { look: 'grimpriest', name: 'Bell-Ringer', talk: [() => "At sunset I ring the Guiding of Souls. Lately, the bell rings back."] },
    },
    signs: { '9,2': () => say(null, "The great bell of the Guiding of Souls. Its rope is black with a thousand years of hands.") },
  },
  // =========================================================================
  terminus1: {
    name: 'Mount Terminus', theme: 'caldera', music: 'grave', under: '.', exitArt: 'floor', worldId: 'ashkar', back: [20, 6], start: [5, 14, 'up'], enc: 'grave', encRate: 0.065, bg: 'volcano',
    rows: [
      "##########################",
      "#Q.UUU###....DDDD....>..##",
      "#..UUU###....DDDD.......##",
      "#........................#",
      "####UU######.#####.####.##",
      "#...UU....DD.#...#.#V....#",
      "#.DDDD....DD...#...#.....#",
      "#.DDDD.UU.....####.#DDD..#",
      "#......UU..L......#.#DDD.#",
      "######.#########..#......#",
      "#.....U....DDD....######.#",
      "#.DD..U....DDD..........##",
      "#.DD..UUUU......DD..C....#",
      "#..........#....DD.......#",
      "#..........#.............#",
      "#####XX###################",
    ],
    warps: { '>': { map: 'terminus2', at: '<' } },
    chests: { Q: { id: 'c2_term1a', item: 'ashhelm' }, V: { id: 'c2_term1b', item: 'salamanderhide' }, C: { id: 'c2_term1c', item: 'hiether' } },
  },
  terminus2: {
    name: 'Mount Terminus - Gate of Eternity', theme: 'caldera', music: 'grave', under: '.', exitArt: 'floor', start: [1, 11, 'right'], bg: 'volcano',
    rows: [
      "######################",
      "#DD..e....aa....e..DD#",
      "#DD......1.........DD#",
      "#....................#",
      "#..DD...UUUUUU...DD..#",
      "#..DD...UUUUUU...DD..#",
      "#....................#",
      "#.e......L.......e...#",
      "#....................#",
      "#DDD....DD..DD....DDD#",
      "#DDD..............DDD#",
      "#.Q..............V...#",
      "#<...................#",
      "######################",
    ],
    warps: { '<': { map: 'terminus1', at: '>' } },
    chests: { Q: { id: 'c2_term2a', item: 'obsidianplate' }, V: { id: 'c2_term2b', item: 'gravecharm' } },
    npcs: { 1: { enemy: 'ferryman', scale: 0.5, name: 'The Ash Ferryman', show: () => !flag('ferryman'), talk: [async () => ferrymanEvent()] } },
    signs: { '10,1': () => say(null, "The Gate of Eternity: an obsidian arch on the edge of the fire. Something on the far side is very, very quiet."), '11,1': () => say(null, "The Gate of Eternity. Pilgrims' tokens hang from it: bones, iron, a child's shoe.") },
    steps: { '8,6': () => !flag('ferryman') && ferrymanEvent(), '9,6': () => !flag('ferryman') && ferrymanEvent(), '10,6': () => !flag('ferryman') && ferrymanEvent(), '11,6': () => !flag('ferryman') && ferrymanEvent(), '12,6': () => !flag('ferryman') && ferrymanEvent(), '13,6': () => !flag('ferryman') && ferrymanEvent() },
  },
  // =========================================================================
  cinders: {
    name: 'The Throne of Cinders', theme: 'caldera', music: 'phoenix', under: '.', exitArt: 'floor', worldId: 'ashkar', back: [38, 9], start: [10, 13, 'up'], bg: 'caldera',
    rows: [
      "######################",
      "#DDDDDDDD.TT.DDDDDDDD#",
      "#DDDDDDD..1...DDDDDDD#",
      "#DDDDDD........DDDDDD#",
      "#DDDD..2......3..DDDD#",
      "#DDD..............DDD#",
      "#DD.....UUUUUU.....DD#",
      "#DD.....UUUUUU.....DD#",
      "#DDD..............DDD#",
      "#DDDD....L.......DDDD#",
      "#DDDDD..........DDDDD#",
      "#DDDDDD........DDDDDD#",
      "#DDDDDDD......DDDDDDD#",
      "#DDDDDDDD....DDDDDDDD#",
      "#DDDDDDDD.XX.DDDDDDDD#",
      "######################",
    ],
    underAt: { '1': '.' },
    npcs: {
      1: { look: 'ashkarman', name: 'Ashkar', show: () => !flag('ch2end'), talk: [async () => throneEvent()] },
      2: { look: 'zealot2', name: 'Zealot', talk: [() => "He is listening. He is always listening. Speak plainly. He hates poetry, unless it's about him."] },
      3: { look: 'zealot2', name: 'Zealot', talk: [() => "What burns may rise. What rises... may be asked to bring snacks. He likes snacks."] },
    },
    steps: { '10,6': () => !flag('throneMet') && throneEvent(), '11,6': () => !flag('throneMet') && throneEvent() },
  },
});
