'use strict';
// ---------------------------------------------------------------------------
// The Final Chapter maps: Godsfall Crater (eight floors down to the Unseated Throne) and the Ring of the Ten.
// The ice and current floors were generated and checked: always solvable, never stuck, no endless loops.
// ---------------------------------------------------------------------------
Object.assign(THEMES, {
  godsfall: { wall: '#3a2a4a', wallDark: '#140a1e', floor: '#4a3e5a', floor2: '#443852', grass: '#3a3a4a', carpet: '#6a3a8a', water: '#2a1a4a', wood: '#3a2a2a', path: '#5a4a6a' },
  prayers: { wall: '#5a5a6a', wallDark: '#22222c', floor: '#6a6a78', floor2: '#626270', grass: '#4a4a5a', carpet: '#8a7a3a', water: '#2a2a4a', wood: '#4a4a4a', path: '#7a7a88' },
  heartgarden: { wall: '#4a2a3a', wallDark: '#1e0e16', floor: '#5a6a4a', floor2: '#546244', grass: '#5a8a4a', mud: '#5a3a3a', water: '#4a6a9a', wood: '#5a3a2a', path: '#8a7a5a', carpet: '#8a3a6a' },
  drownedsun: { wall: '#8a6a2a', wallDark: '#3a2a0a', floor: '#c8a050', floor2: '#bc9444', grass: '#a0803a', water: '#3a5a8a', wood: '#6a4a1a', path: '#d8b060', carpet: '#e0b030' },
  nightcore: { wall: '#1a1028', wallDark: '#06040c', floor: '#241a34', floor2: '#20162e', grass: '#1a1a2a', water: '#0a0a1a', wood: '#1a1020', path: '#2a2040', carpet: '#3a1a5a' },
  godsdeep: { wall: '#2a2030', wallDark: '#0a060e', floor: '#3a3040', floor2: '#342a3a', grass: '#2a2a2a', carpet: '#6a2a2a', water: '#1a1a2a', wood: '#2a1a1a', path: '#4a3a4a' },
  throne: { wall: '#e8dcc0', wallDark: '#6a5a40', floor: '#f0e8d0', floor2: '#e6dcc4', grass: '#c8c0a0', carpet: '#8a6ac0', water: '#4a3a8a', wood: '#9a7a40', path: '#f0e8d0' },
  seatring: { wall: '#8a9ab8', wallDark: '#3a4a68', floor: '#d8e0f0', floor2: '#ccd6ea', grass: '#c8d8f0', carpet: '#e0b030', water: '#6a9ae8', wood: '#8a7a6a', path: '#e0e8f8' },
});
Object.assign(TILE_ART, {
  sunglass(P, th, rng) { P.r(0, 0, 15, 15, '#e8c060'); P.r(0, 15, 15, 15, '#c09030'); P.r(15, 0, 15, 15, '#c09030'); for (let i = 0; i < 3; i++) { const x = Math.floor(rng() * 10) + 1, y = Math.floor(rng() * 12) + 1; P.r(x, y, x + 3, y, '#fff4c0'); } },
  nightrock(P, th, rng) { TILE_ART.floor(P, th, rng, 0, 0); P.r(2, 5, 13, 14, '#120a1c'); P.r(3, 3, 12, 12, '#2a1a3a'); P.p(5, 5, '#8060c0'); P.p(10, 8, '#8060c0'); },
  seatring(P, th, rng, f) { P.r(0, 0, 15, 15, '#2a5ab8'); P.circ(8, 8, 7, '#d8e0f0'); P.circ(8, 8, 5, '#8a9ab8'); for (let i = 0; i < 10; i++) { const a = i / 10 * Math.PI * 2; P.p(8 + Math.round(Math.cos(a) * 6), 8 + Math.round(Math.sin(a) * 6), (i + f) % 3 ? '#ffb030' : '#ffe070'); } },
  emptyseat(P, th, rng, f) { TILE_ART.floor(P, th, rng, 0, 0); P.r(4, 2, 11, 13, '#6a5a40'); P.r(5, 3, 10, 9, '#2a2030'); P.r(3, 9, 12, 11, '#8a7a5a'); P.r(4, 12, 5, 15, '#6a5a40'); P.r(10, 12, 11, 15, '#6a5a40'); if (f % 2) P.p(7, 5, '#c080ff'); },
});
Object.assign(WORLD_TILES, { 8: { art: 'seatring', place: true, anim: 3 } });
// the Ring of the Ten: a reef-ringed islet in the sea east of Zalakir, where the gods hold court
[['~xxx~', 3], ['x.8.x', 4], ['~xxx~', 5]].forEach(([s, y]) => _patch(MAPS.zalakir.rows, y, 47, s));
MAPS.zalakir.places['49,4'] = { map: 'seatring', sky: true, check: async () => { if (!flag('ch6start')) { await say(null, "A ring of white stone on a tiny islet. Ten empty pedestals. It hums, faintly, like a held breath."); return false; } return true; } };

const GF_ICE = [
  "###############>######",
  "#iiioiiiiiiiiiiiiiiii#",
  "#oiiiiiiiiiioiiiiiiii#",
  "#iiiiiooiiiiioiiiioii#",
  "#iiiiiiioiiiiiiiioiii#",
  "#ioiiiiiiiiiiioiooi.i#",
  "#ioiiiioiiioiioiioiii#",
  "#iiiiiiiiiiiiiioiiiii#",
  "#iiiiiiiiioiiiiiiiiii#",
  "#oioiiiiiiiiiiioiiiii#",
  "#iioiiiiiioiiiiioiiii#",
  "#iiiii.iiiiiiiiiiooii#",
  "#iiiiiiiiiiiiiiiiiiii#",
  "#..........<.........#",
  "######################",
];
const GF_CUR = [
  "#############>##########",
  "#...|...{..}|{{{|...[..#",
  "#.|{...||.{.[...}|[..}|#",
  "#}..[.{...}...[.[{{...}#",
  "#.}....[{...[..|[{].[..#",
  "#........[[...{..{.}.[}#",
  "#]].......}.[.[.......[#",
  "#}...}{...[...{.[.{}...#",
  "#.{}{..]...[|[.}.]..|..#",
  "#[[..|{}...]..|}..}{[..#",
  "#.}...{..}...}.]..[.[|]#",
  "#.....{......]]}...{...#",
  "#{{.....{..}]}{.|..|.{]#",
  "#{.{.]..|{[.[....}}..}{#",
  "#......................#",
  "#...........<..........#",
  "########################",
];
const GF_PETALS = [
  "##########>###########",
  "#.{...}.}..|}]....[..#",
  "#|.|.].[.{....{..].|{#",
  "#..{...}|...{....{...#",
  "#|{[}.......{{.{..|}.#",
  "#...|.]}.{.]}}..|...[#",
  "#...[.}.}.[.]..{}}...#",
  "#...}}...[|.]|[...}.]#",
  "#]]...]...{.}..[...{.#",
  "#..[.|[....}}}.[....[#",
  "#......[.......|..}{[#",
  "#.}.{[{.{{..{.[...[.[#",
  "#....................#",
  "#..........<.........#",
  "######################",
];
// the Hall of Unanswered Prayers: echoes of people from the whole journey (events6.js gives them their words)
const PRAYER_ECHOES = [[4, 3], [17, 3], [3, 7], [18, 7], [6, 11], [15, 11]];
// the Ring of the Ten: one pedestal per god, in a circle
const RING_SEATS = [[11, 2], [16, 3], [19, 6], [19, 10], [16, 13], [11, 14], [6, 13], [3, 10], [3, 6], [6, 3]];
const RING_GODS = ['sylara', 'thalara', 'valerion', 'myndra', 'grimnar', 'elaris', 'malakar', 'kryos', 'zariel', 'tenth'];
const ringRows = (() => {
  const W = 23, H = 17, g = Array.from({ length: H }, (_, y) => Array.from({ length: W }, (_, x) => (x === 0 || y === 0 || x === W - 1 || y === H - 1) ? '#' : '.'));
  for (const [x, y] of RING_SEATS) g[y][x] = 'e';
  for (let y = 6; y <= 10; y++) for (let x = 9; x <= 13; x++) g[y][x] = '_';
  g[8][11] = 'a'; g[H - 1][11] = 'X'; g[H - 2][11] = '.'; g[14][3] = 'L';
  return g.map(r => r.join(''));
})();

Object.assign(MAPS, {
  gf1: {
    name: 'Godsfall - The Breach', theme: 'godsfall', music: 'storm', under: ':', exitArt: 'floor', worldId: 'zalakir', back: [33, 14], start: [2, 2, 'down'], enc: 'godsfall', encRate: 0.045, bg: 'stormplain',
    rows: [
      "^^^^^^^^^^^^^^^^^^^^^^^^",
      "X:::::^^^^:::::::::^^^^^",
      "^:::::^^^::::^^^:::::^^^",
      "^^^:::::::::^^^^^^:::::^",
      "^^^^^^^^:::::::^^^^^::^^",
      "^^:::Q^^^^^^:::::::::::^",
      "^^::::::::^^^^^^^^^^:::^",
      "^^^^^::::::::::::^^^:::^",
      "^:::^^^^^^^^^::::::::::^",
      "^:::::::::::^^^^^^^^:^^^",
      "^:L::^^^^^:::::::::::::^",
      "^^^:::::::::::^^^^^^^:^^",
      "^^^^^^^^^^^^::::V^^^:::^",
      "^^^^^^^^^^^^^^^^^^^^^>^^",
    ],
    warps: { '>': { map: 'gf2', at: '<' } },
    chests: { Q: { id: 'c6_g1a', item: 'godsdew', n: 3 }, V: { id: 'c6_g1b', item: 'halohelm' } },
    steps: { '6,3': () => godsfallMoment(1), '7,3': () => godsfallMoment(1) },
  },
  gf2: {
    name: 'Godsfall - The Hall of Unanswered Prayers', theme: 'prayers', music: 'veil', under: '.', exitArt: 'floor', start: [10, 14, 'up'], enc: 'godsfall', encRate: 0.03, bg: 'chapel',
    rows: [
      "######################",
      "##########>###########",
      "#........GGG.........#",
      "#...1............2...#",
      "#....................#",
      "#..o......___.....o..#",
      "#.........___........#",
      "#..3......___.....4..#",
      "#.........___........#",
      "#..o......___.....o..#",
      "#.........___........#",
      "#.....5...___...6....#",
      "#.Q...............V..#",
      "#.....L..............#",
      "#..........<.........#",
      "######################",
    ],
    tileOverride: c => c === 'G' ? (num('prayersAnswered') >= 3 ? IN_TILES._ : { art: 'stargate', solid: true, anim: 2 }) : null,
    overlay(cx, cy) { PRAYER_ECHOES.forEach(([x, y], i) => { if (flag('prayer' + i)) glowAt(x, y, cx, cy, 'rgba(255,240,180,0.45)'); }); },
    warps: { '<': { map: 'gf1', at: '>' }, '>': { map: 'gf3', at: '<' } },
    npcs: Object.fromEntries(PRAYER_ECHOES.map((p, i) => [i + 1, { look: 'shade', name: 'An Unanswered Prayer', fixed: true, talk: [async () => prayerEcho(i)] }])),
    chests: { Q: { id: 'c6_g2a', item: 'answeredprayer' }, V: { id: 'c6_g2b', item: 'lastlight', n: 3 } },
  },
  gf3: {
    name: 'Godsfall - The Heartseed Garden', theme: 'heartgarden', music: () => flag('ch6heartseed') ? 'vale' : 'drowned', under: '.', exitArt: 'floor', start: [11, 13, 'up'], enc: 'heartgarden', encRate: 0.04, bg: 'vale',
    rows: GF_PETALS.map(r => r.replace('>', '>')),
    tileOverride: c => c === '|' ? { art: 'rootwall', solid: true } : null,
    warps: { '<': { map: 'gf2', at: '>' }, '>': { map: 'gf3b', at: '<' } },
    steps: { '10,13': () => godsfallMoment(3), '12,13': () => godsfallMoment(3) },
  },
  gf3b: {
    name: 'Godsfall - The Heart of the Garden', theme: 'heartgarden', music: () => flag('ch6heartseed') ? 'vale' : 'sorrow', under: 'g', exitArt: 'floor', start: [10, 12, 'up'], bg: 'vale',
    rows: [
      "'''''''''''''''''''''",
      "'nnnnnnnnn>nnnnnnnnn'",
      "'ggggggggGGGgggggggg'",
      "'gggggggg-1-gggggggg'",
      "'gFgggggg---ggggggFg'",
      "'ggggggg-----ggggggg'",
      "'ggggggg-----ggggggg'",
      "'ggQgggg-----ggggVgg'",
      "'ggggggg-----ggggggg'",
      "'gFggggg-----gggggFg'",
      "'ggggLgggggggggggggg'",
      "'ggggggggggggggggggg'",
      "'ggggggggg<ggggggggg'",
      "'''''''''''''''''''''",
    ],
    tileOverride: c => c === 'G' ? (flag('ch6heartseed') ? IN_TILES.g : { art: 'vine', solid: true }) : c === '-' && flag('ch6heartseed') ? IN_TILES.g : null,
    warps: { '<': { map: 'gf3', at: '>' }, '>': { map: 'gf4', at: '<' } },
    npcs: { 1: { enemy: 'heartseedthrall', scale: 0.34, name: 'The Heartseed Thrall', show: () => !flag('ch6heartseed'), talk: [async () => heartseedEvent()] } },
    chests: { Q: { id: 'c6_g3a', item: 'gardenrobe' }, V: { id: 'c6_g3b', item: 'godsdew', n: 3 } },
    steps: { '9,6': () => heartseedEvent(), '10,6': () => heartseedEvent(), '11,6': () => heartseedEvent() },
  },
  gf4: {
    name: 'Godsfall - The Drowned Sun', theme: 'drownedsun', music: 'tower', under: '.', exitArt: 'floor', start: [11, 13, 'up'], enc: 'drownedsun', encRate: 0.035, bg: 'temple',
    rows: GF_ICE,
    tileOverride: c => c === 'i' ? { art: 'sunglass', ice: true } : null,
    warps: { '<': { map: 'gf3b', at: '>' }, '>': { map: 'gf4b', at: '<' } },
    steps: { '10,13': () => godsfallMoment(4), '12,13': () => godsfallMoment(4) },
  },
  gf4b: {
    name: 'Godsfall - The Sun\'s Grave', theme: 'drownedsun', music: () => flag('ch6dawnheart') ? 'tower' : 'sorrow', under: '.', exitArt: 'floor', start: [10, 12, 'up'], bg: 'temple',
    rows: [
      "#####################",
      "#oooooooo.>.oooooooo#",
      "#........GGG........#",
      "#.........1.........#",
      "#........___........#",
      "#..o.....___.....o..#",
      "#........___........#",
      "#..Q.....___.....V..#",
      "#........___........#",
      "#..o.....___.....o..#",
      "#....L...___........#",
      "#........___........#",
      "#.........<.........#",
      "#####################",
    ],
    tileOverride: c => c === 'G' ? (flag('ch6dawnheart') ? IN_TILES['.'] : { art: 'stargate', solid: true, anim: 2 }) : null,
    warps: { '<': { map: 'gf4', at: '>' }, '>': { map: 'gf5', at: '<' } },
    npcs: { 1: { enemy: 'dawnheartseraph', scale: 0.34, name: 'The Dawnheart Seraph', show: () => !flag('ch6dawnheart'), talk: [async () => dawnheartEvent()] } },
    chests: { Q: { id: 'c6_g4a', item: 'sunkenplate' }, V: { id: 'c6_g4b', item: 'starmilk', n: 3 } },
    steps: { '9,6': () => dawnheartEvent(), '10,6': () => dawnheartEvent(), '11,6': () => dawnheartEvent() },
  },
  gf5: {
    name: 'Godsfall - Nyxia\'s Night', theme: 'nightcore', music: 'veil', under: '.', exitArt: 'floor', start: [12, 15, 'up'], enc: 'starlessnight', encRate: 0.035, bg: 'chapel',
    rows: GF_CUR,
    tint: () => 'rgba(20,0,40,0.25)',
    tileOverride: c => c === '|' ? { art: 'nightrock', solid: true } : null,
    warps: { '<': { map: 'gf4b', at: '>' }, '>': { map: 'gf5b', at: '<' } },
    steps: { '11,15': () => godsfallMoment(5), '13,15': () => godsfallMoment(5) },
  },
  gf5b: {
    name: 'Godsfall - The Heart of the Night', theme: 'nightcore', music: () => flag('ch6night') ? 'veil' : 'sonia', under: '.', exitArt: 'floor', start: [10, 12, 'up'], bg: 'chapel',
    rows: [
      "#####################",
      "#;;;;;;;;.>.;;;;;;;;#",
      "#;.......GGG.......;#",
      "#;........1........;#",
      "#;.......___.......;#",
      "#;..o....___....o..;#",
      "#;.......___.......;#",
      "#;.Q.....___.....V.;#",
      "#;.......___.......;#",
      "#;..o....___....o..;#",
      "#;...L...___.......;#",
      "#;.......___.......;#",
      "#;........<........;#",
      "#####################",
    ],
    tint: () => flag('ch6night') ? null : 'rgba(20,0,40,0.3)',
    tileOverride: c => c === 'G' ? (flag('ch6night') ? IN_TILES['.'] : { art: 'stargate', solid: true, anim: 2 }) : null,
    warps: { '<': { map: 'gf5', at: '>' }, '>': { map: 'gf6', at: '<' } },
    npcs: { 1: { look: 'verai', name: 'Verai', show: () => !flag('ch6night') && !flag('ch6nightActor') && veraiAwayInGodsfall(), talk: [async () => nightEvent()] } },
    chests: { Q: { id: 'c6_g5a', item: 'starlessmail' }, V: { id: 'c6_g5b', item: 'godsdew', n: 3 } },
    steps: { '9,6': () => nightEvent(), '10,6': () => nightEvent(), '11,6': () => nightEvent() },
  },
  gf6: {
    name: 'Godsfall - Where the Gods Fell', theme: 'godsdeep', music: () => flag('ch6rescue') ? 'vale' : 'keep', under: '.', exitArt: 'floor', start: [11, 15, 'up'], enc: 'godsdeep', encRate: 0.03, bg: 'grave',
    rows: [
      "########################",
      "###########>############",
      "#..........GG..........#",
      "#..o..o...........o..o.#",
      "#..........1...........#",
      "#.........____.........#",
      "#..J...J..____..J...J..#",
      "#.........____.........#",
      "#..J...J..____..J...J..#",
      "#.........____.........#",
      "#.Q.......____.......V.#",
      "#.........____.........#",
      "#....L....____.........#",
      "#.........____.........#",
      "#......................#",
      "#..........<...........#",
      "########################",
    ],
    tileOverride: c => c === 'G' ? (flag('ch6rescue') ? IN_TILES['.'] : { art: 'stargate', solid: true, anim: 2 }) : null,
    warps: { '<': { map: 'gf5b', at: '>' }, '>': { map: 'gf7', at: '<' } },
    npcs: { 1: { enemy: 'chainwarden', scale: 0.32, name: 'The Chainwarden', show: () => !flag('ch6warden'), talk: [async () => deepEvent()] } },
    chests: { Q: { id: 'c6_g6a', item: 'lastlight', n: 3 }, V: { id: 'c6_g6b', item: 'seatplate' } },
    steps: { '10,8': () => deepEvent(), '11,8': () => deepEvent(), '12,8': () => deepEvent(), '13,8': () => deepEvent() },
  },
  gf7: {
    name: 'Godsfall - The Stair of Every Prayer', theme: 'throne', music: 'sorrow', under: '.', exitArt: 'floor', start: [11, 13, 'up'], bg: 'temple',
    rows: [
      "#######################",
      "##########>############",
      "#.........._..........#",
      "#.........._..........#",
      "#..o......._.......o..#",
      "#.........___.........#",
      "#........_____........#",
      "#.......W_____W.......#",
      "#.........___.........#",
      "#..o...L..._...1...o..#",
      "#.........._..........#",
      "#.........._..........#",
      "#.........._..........#",
      "#..........<..........#",
      "#######################",
    ],
    shops: 'lastmerchant',
    warps: { '<': { map: 'gf6', at: '>' }, '>': { map: 'gf8', at: '<' } },
    npcs: { 1: { look: 'merchant', name: 'The Last Merchant', talk: [async () => lastMerchant()] } },
    steps: { '11,9': () => lastCamp(), '10,9': () => lastCamp(), '12,9': () => lastCamp() },
  },
  gf8: {
    name: 'The Unseated Throne', theme: 'throne', music: 'final', under: '.', exitArt: 'floor', start: [11, 13, 'up'], bg: 'sanctum',
    rows: [
      "#######################",
      "#........aaaaa........#",
      "#..........T..........#",
      "#.........___.........#",
      "#..o......___......o..#",
      "#.........___.........#",
      "#.........___.........#",
      "#..o......___......o..#",
      "#.........___.........#",
      "#.........___.........#",
      "#..o......___......o..#",
      "#.........___.........#",
      "#.........___.........#",
      "#..........<..........#",
      "#######################",
    ],
    warps: { '<': { map: 'gf7', at: '>' } },
    steps: { '10,8': () => seatThroneEvent(), '11,8': () => seatThroneEvent(), '12,8': () => seatThroneEvent() },
  },
  seatring: {
    name: 'The Ring of the Ten', theme: 'seatring', music: 'title', under: '.', exitArt: 'floor', worldId: 'zalakir', back: [49, 4], start: [11, 15, 'up'], bg: 'sanctum', skyBack: true,
    rows: ringRows,
    signs: Object.fromEntries([...RING_SEATS.map(([x, y], i) => [x + ',' + y, () => godTrial(i)]), ['11,8', () => ringAltar()]]),
  },
});
