'use strict';
// ---------------------------------------------------------------------------
// World map + interior maps. Story events live in events.js.
// World of Cael'Brithar - the continent of Aurelion, Bastion of Light.
// ---------------------------------------------------------------------------
const WORLD = {
  id: 'world', name: 'Aurelion', world: true, theme: 'world', music: 'field',
  rows: [
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
    "~~~~~s.ss.ss.s^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^~~~~~~~~~~~~~~",
    "~~~~~.^^^^^...^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^~~~~~~~~~~~",
    "~~~~~^^^^^^^^.^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ss~~~~~~~~",
    "~~~^^^^.f.^^^^f^ff^ff^..^..^..^..r..^..^..^..^..^...ss.~~~~~",
    "~~~^^.f....f^^ffffffff...........r....................s~~~~~",
    "~~~^^....f..^^^ffffffff..........r....................s~~~~~",
    "~~~^...f....D^^ffffffff..........r......f..............~~~~~",
    "~~~^.f..V.f..^^ffffffff..........r....fffff...........s~~~~~",
    "~~~^....f....^...Dffffff...C.....r...fffffff..........s~~~~~",
    "~~~^^.f....f^^^ffffffff..........r..fffffffff........s~~~~~~",
    "~~~^^....f..^^fffffffff..........r...fffffff..........~~~~~~",
    "~~~^^^^f..^^^^fffffffff..........r....fffff..........~~~~~~~",
    "~~~.^^^^.^^^^fffffffff...........r......f............s~~~~~~",
    "~~~s..^^G^^..fffffffff...........r....................~~~~~~",
    "~~~~..........fffffff............r.............f......s~~~~~",
    "~~~~~s...........f...............r...........fffff.....~~~~~",
    "~~~~~............................B..........fffffff...s~~~~~",
    "~~~~~~s..........................r...........fffff....s~~~~~",
    "~~~~~s...............T...........r.............f.......~~~~~",
    "~~~~~.................f..........r....................s~~~~~",
    "~~~~...............fffffff.......r....................s~~~~~",
    "~~~...............fffffffff......r............P........~~~~~",
    "~~~s...............fffffff.......r....................s~~~~~",
    "~~~s..................f..........r....................s~~~~~",
    "~~~~s............................r.....................~~~~~",
    "~~~~~....................^^^^....r....^^^.........sssssH~~~~",
    "~~~~~~s..................^^^^....r....^^^............ss~~~~~",
    "~~~~~~~s.........................r..................s~~~~~~~",
    "~~~~~~~~.................s.ss.~s.rs..............ss~~~~~~~~~",
    "~~~~~~~~~s..............s~~~~~~~~r~~~~~~~~~~~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~ss.ss.ss.ss.ss~~~~~~~~~r~~~~~~~~~~~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~s.^.^.s~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~s^^^...^^^s~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~s^^.......^^s~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~s.^....E....^..~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.^^.......^^.~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~s^^^...^^^.~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~s.^^^ss~~~~~~~~~~~~~~~~",
    "~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~",
  ],
  // world tile -> interior map entrance
  places: {
    '27,11': { map: 'solanthia', check: () => solanthiaGate() },
    '17,11': { map: 'silverleaf1' },
    '12,9': { map: 'silverleaf2', at: [1, 4, 'right'] },
    '8,10': { map: () => flag('votary') ? 'hollowash' : 'hollowmere' },
    '21,21': { map: 'goldengrove' },
    '46,24': { map: 'brightwater' },
    '55,28': { map: 'tower1', check: () => towerGate() },
    '40,37': { map: 'embrace1' },
  },
  zone(x, y, t) {
    if (t === '~') return 'sea';
    if (t === 'r' || t === 'B') return 'river';
    if (y >= 33) return 'embrace';
    if (x < 14 && y < 17) return flag('votary') ? 'hollow' : 'silverleaf';
    if (t === 'f' && x < 25 && y < 19) return 'silverleaf';
    if (x > 40 && y > 20) return 'coast';
    if (y >= 17) return 'meadow';
    return 'aurel';
  },
  bg(x, y, t) {
    if (t === '~' || t === 'r' || t === 'B') return 'sea';
    if (y >= 33) return 'vale';
    if (x < 14 && y < 17 && flag('votary')) return 'burning';
    if (t === 'f') return 'forest';
    if (t === 's') return 'beach';
    if (y >= 17) return 'meadow';
    return 'plains';
  },
};

const MAPS = {
  // =========================================================================
  barge: {
    name: 'The Gilded Wake', theme: 'barge', music: 'prelude', under: 'd', start: [7, 6, 'up'], tint: 'rgba(10,20,70,0.35)',
    rows: [
      "~~~~~~~~~~~~~~~~",
      "~qqqqqqqqqqqqqq~",
      "~qdddddvdddddq~~",
      "~qdpdd2ddd3dpq~~",
      "~qdddddddddddq~~",
      "~qdd4ddddddd5q~~",
      "~qdddddddddddq~~",
      "~qdpdddddddpdq~~",
      "~qqqqqqqqqqqqq~~",
      "~~~~~~~~~~~~~~~~",
    ],
    npcs: {
      2: { look: 'tamsin', name: 'Warden Tamsin', talk: [() => "Solanthia by dawn, Captain. The river's quiet tonight. Too quiet, if you ask me. Which nobody does."] },
      3: { look: 'warden', name: 'Warden', talk: [() => "The oracles in Moonshadow Cove just... handed it over. Didn't even ask why. I keep thinking about that."] },
      4: { look: 'warden', name: 'Warden', talk: [() => "I heard the Lantern's flame was lit the night Nyxia died, and hasn't flickered since. Gives me chills."] },
      5: { look: 'miasma', name: 'Miasma', talk: [() => "My contract says 'relic recovery.' It does not say 'rowing.' I want that on record."] },
    },
    signs: { '7,2': () => say(null, 'The Veil Lantern sits in its iron cage. Its violet flame is perfectly still, even in the river wind.') },
  },
  // =========================================================================
  solanthia: {
    name: 'Solanthia, City of Dawn', theme: 'solanthia', music: 'town', under: 'g', exitArt: 'path', back: [27, 12], start: [14, 17, 'up'],
    rows: [
      "tttttttttttRRRRRRRRttttttttttt",
      "tgggggggggtRRRRRRRRtgggggggggt",
      "tgRRRRRggggbbbb+bbbggggRRRRRgt",
      "tgRRRRRgggg,,,,,,,,ggggRRRRRgt",
      "tgbbWbbgggg,,,,,,,,ggggbbAbbgt",
      "tg,,,,,,,,,,,,,,,,,,,,,,,,,,gt",
      "tgggg1ggggg,,,,,,,,gggg2gggggt",
      "tgFFFggggg,,,,OO,,,,gggggFFFgt",
      "tgFFFggggg,,,,OO,,,,gggggFFFgt",
      "tgggggggg3,,,,,,,,,,4ggggggggt",
      "tgRRRRRggg,,,,,,,,,,gggRRRRRgt",
      "tgbbNbbggg,,,,,,,,,,gggbbHbbgt",
      "tg,,,,,,,,,,,,,,,,,,,,,,,,,,gt",
      "tggg5gggggg,,,,,,,,gggggg6gggt",
      "tgRRRRRgggg,,,,,,,,ggggRRRRRgt",
      "tgbbIbbgggg,,,,,,,,ggggbb+bbgt",
      "tg,,,,,,,,,,,,,,,,,,,,,,,,,,gt",
      "tgggg7ggggg,,,,,,,,ggggg8ggggt",
      "tttttttttttttXXXXttttttttttttt",
    ],
    shops: 'solanthia',
    doors: { '15,2': { map: 'temple', x: 10, y: 10, dir: 'up' }, '25,15': { map: 'quarters', x: 5, y: 4, dir: 'up' } },
    npcs: {
      1: { look: 'man', move: 'wander', talk: [() => !flag('mission') && "Dawn Prayer's at sunrise, same as every day. The Great Lens turns the first light into a sunbeam you could lean on.", () => "The High Luminar gave another sermon on 'vigilance.' Everyone clapped. I think I clapped. I was mostly thinking about lunch."] },
      2: { look: 'luna', name: 'Dame Luna', show: () => !flag('mission'), talk: [async () => { await say('Dame Luna', "Welcome home, Captain Cudlar! The High Luminar is expecting you at the Grand Temple."); await say(null, "The knight leans toward Miasma and sniffs. Twice."); await say('Dame Luna', "...You smell like smoke and old gold. Sorry! Knight thing. We sniff. For safety."); await say(MI(), "That is NOT a knight thing."); return null; }] },
      3: { look: 'priest', name: 'Priest', talk: [() => "Sylara's teaching: light brings truth. Every day is a second chance. Be the dawn in others' lives. ...The High Luminar has been adding footnotes lately."] },
      4: { look: 'woman', move: 'wander', talk: [() => "My cousin in Goldengrove says the Dawnguard raised the Aurora Bridge last week. 'To keep heretics out.' Out of where? It's a bridge."] },
      5: { look: 'child', move: 'wander', talk: [async () => { await say('Child', "Whoa! Is that a DRAGON? Are you on fire? Can you do a fire?"); await say(HERO('miasma'), "Five silver and you've got yourself a fire."); await say(HERO('raine'), "Miasma."); await say(HERO('miasma'), "...First one's free."); return null; }] },
      6: { look: 'scholar', name: 'Scholar', talk: [() => "Only ten gods exist at once. The Ascendant Ten. Lose enough worshippers and you simply... stop. Nyxia, the Veiled Night, stopped a year ago. The Tenth Flame took her seat. I'm told it's rude to bring it up."] },
      7: { look: 'oldman', talk: [() => "A Bedroll's worth its weight in gold on the road. Rest beside any Dawn Lantern, or out on open ground, and wake up good as new."] },
      8: { look: 'dawnguard', name: 'Gate Guard', talk: [() => !flag('mission') && "The roads west run toward the Silverleaf Wood. Pale trees, pale wolves. Don't go poking around there without a reason.", () => "Silverleaf is west, past the bend in the Dawnpeaks. Mind the wolves."] },
    },
  },
  // =========================================================================
  temple: {
    name: 'Grand Temple of the Dawn', theme: 'temple2', music: 'castle', under: '.', exitArt: 'carpet', start: [10, 10, 'up'],
    exitTo: null, back: { map: 'solanthia', x: 15, y: 3, dir: 'down' },
    rows: [
      "#####################",
      "#e..*....GaG....*..e#",
      "#.........1.6.......#",
      "#...o....___....o...#",
      "#.2......___......3.#",
      "#...o....___....o...#",
      "#.......G___G.......#",
      "#...o....___....o...#",
      "#..4.....___.....5..#",
      "#...o....___....o...#",
      "#......L.___........#",
      "#########___#########",
      "#########XXX#########",
    ],
    npcs: {
      1: { look: 'vesper', name: 'High Luminar Vesper', show: () => !flag('mission'), talk: [async () => vesperAudience()] },
      2: { look: 'dawnguard', name: 'Dawnguard', talk: [() => "Stand straight in the Light, citizen."] },
      3: { look: 'dawnguard', name: 'Dawnguard', talk: [() => "The High Luminar arrived from the east two winters ago. The Sun Queen fell ill that same spring. Nobody's seen her since. Strange coincidence."] },
      4: { look: 'priest', name: 'Priest', talk: [() => "The Great Lens focuses Sylara's first light onto the altar each dawn. Lately it's been... dimmer. I polish it twice a day now."] },
      6: { look: 'odeaon', name: 'High Knight Odeaon', show: () => !flag('mission'), talk: [() => flag('audience') ? "Go carefully, Raine. ...And keep that mercenary close. Closer than you think you need to." : "Report to the Luminar first, Captain. We can speak after."] },
      5: { look: 'warden', name: 'Warden', talk: [() => "Nine relics recovered this year, Captain. Every one from a shrine of a god that isn't Sylara. I don't know what the Luminar wants with them all."] },
    },
    signs: { '10,1': () => say(null, 'The dawn altar. A sunburst is carved into its face, worn smooth by a thousand years of hands.') },
  },
  quarters: {
    name: 'Warden Quarters', theme: 'house', music: 'town', under: '.', exitArt: 'floor', start: [5, 4, 'up'],
    back: { map: 'solanthia', x: 25, y: 16, dir: 'down' },
    rows: [
      "###########",
      "#kk.u..u.k#",
      "#.........#",
      "#.$$...1..#",
      "#.........#",
      "#####X#####",
    ],
    npcs: {
      1: { look: 'miasma', name: 'Miasma', show: () => flag('audience') && !flag('mission'), talk: [async () => quartersNight()] },
    },
  },
  // =========================================================================
  silverleaf1: {
    name: 'Silverleaf Wood', theme: 'silver', music: 'forest', under: 'g', exitArt: 'path', back: [18, 11], start: [26, 9, 'left'], enc: 'silverleaf', encRate: 0.07, bg: 'forest',
    rows: [
      "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
      "BQg,gBBgggggBBBBgggggggBBggB",
      "Bgg,ggBgg,ggggBBgg,,,ggBBggB",
      "BBg,,ggg,,,gggggg,,B,gggg,gB",
      "BBgggBBBgg,BBBBgg,BBB,ggg,gB",
      "B>,,gBBBBg,,BwwBg,,gg,BB,,gB",
      "Bgg,gBgggg,gBwwBgg,gg,,,,ggB",
      "BBg,,,,g,,,gBBBBgggBBgggBBgB",
      "BBBBgg,,,gggggLgggBBBgg,ggBB",
      "BVggggBBB,,BBBgg,,,,,,,,,,,X",
      "BggggBBBBg,,,BBgggBBBgggBBgX",
      "BBgggggBgg,gg,,,,,gBBBggBBgB",
      "BBBBgggBBg,ggBBBg,ggggggggZB",
      "BwwBBgg,,,,gggBBg,,BBBBggggB",
      "BwwwBBBBgggggBBBBgggggBBBBBB",
      "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
    ],
    warps: { '>': { map: 'silverleaf2', at: '<' } },
    chests: { Q: { id: 'c_sl1a', item: 'tonic', n: 2 }, V: { id: 'c_sl1b', item: 'featherhat' }, Z: { id: 'c_sl1c', gold: 200 } },
  },
  silverleaf2: {
    name: 'Silverleaf Wood - Stag\'s Hollow', theme: 'silver', music: 'forest', under: 'g', exitArt: 'path', back: [18, 11], back2: [12, 10], start: [26, 1, 'down'], enc: 'silverleaf', encRate: 0.07, bg: 'deepwood',
    tint: 'rgba(20,40,60,0.18)',
    rows: [
      "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
      "BBBBggggBBBBBgggggBBBBgggg<B",
      "BBBgggggggBBggg,gggBBgg,,,gB",
      "YggggggggggBBBg,,BBBgg,BB,gB",
      "Yggg1gggggggggg,gggg,,,BB,gB",
      "BBgggggggggBBBB,BBBg,BBBg,gB",
      "BBggggggggBBBBg,BQBg,,,,,,gB",
      "BBBBggggBBBBgg,,Bg,,gBBBB,BB",
      "BBBBBBgggBBgg,,BBBg,gBwwwB,B",
      "BBwwBBBg,,,,,,BBBBg,gBwwBg,B",
      "BBwwwBBBgLgBBBgggg,,ggBBgg,B",
      "BBBBBBBBBgggggggBBBggg,,,,VB",
      "BBBBBBBBBBBBBBBBBBBBBBBBBBBB",
    ],
    warps: { '<': { map: 'silverleaf1', at: '>' } },
    chests: { Q: { id: 'c_sl2a', item: 'emberplume' }, V: { id: 'c_sl2b', item: 'embercharm' } },
    npcs: {
      1: { img: 'b_veilstag', scale: 0.36, name: 'The Veilstag', show: () => !flag('stag'), talk: [async () => veilstagEvent()] },
    },
    steps: {
      '9,2': () => !flag('stag') && veilstagEvent(), '9,3': () => !flag('stag') && veilstagEvent(), '9,4': () => !flag('stag') && veilstagEvent(), '9,5': () => !flag('stag') && veilstagEvent(), '9,6': () => !flag('stag') && veilstagEvent(),
    },
  },
  // =========================================================================
  hollowmere: {
    name: 'Hollowmere', theme: 'hollow', music: 'elf', under: 'g', exitArt: 'path', back: [8, 11], start: [12, 13, 'up'],
    rows: [
      "tttttttttttttttttttttttttt",
      "tgggFFgggtgggggggtgggggFFt",
      "tgRRRRRggggggaggggggRRRRRt",
      "tgRRRRRgggggg,ggggggRRRRRt",
      "tgbbIbbgggggg,ggggggbbbbbt",
      "tg,,,,,,,,,,,,,,,,,,,,,,,t",
      "tggg1ggggg2ggg,ggg3ggg4ggt",
      "tgtgggggggggg,,gggggggtggt",
      "tggggRRRRRggg,,ggRRRRRgggt",
      "tggggRRRRRggg,,ggRRRRRgggt",
      "tggggbbNbbggg,,ggbbbbbgggt",
      "tgggg,,,,,,,,,,,,,,,,gg5gt",
      "tgFFgg6ggggg,,ggggggg7ggFt",
      "tgggggggggggg,,ggggggggggt",
      "ttttttttttttXXtttttttttttt",
    ],
    shops: 'hollowmere',
    npcs: {
      1: { look: 'hollowman', move: 'wander', talk: [() => "Visitors from Solanthia? We don't get many. We don't get ANY. Welcome to Hollowmere, I suppose."] },
      2: { look: 'hollowwoman', move: 'wander', talk: [() => "The smoke? Oh, it follows the ones who still dream of her. Nyxia, I mean. The goddess you're not supposed to miss."] },
      3: { look: 'verai', name: 'Verai', talk: [async () => hollowmereArrival()] },
      4: { look: 'elder', name: 'Elder Moth', talk: [() => "When a god dies, her faithful don't stop believing all at once. They just... whisper. We are the whisper, Captain Cudlar."] },
      5: { look: 'child', move: 'wander', talk: [() => "Everyone says Verai's a witch. But she gave me a smoke bunny once. Are you her friend? The one who left?"] },
      6: { look: 'oracle', name: 'Oracle Sef', talk: [() => "I dreamed of a golden woman who does not blink. She was standing in our square. You're not her, are you? ...Good."] },
      7: { look: 'hollowman', talk: [() => "The Veilstag guards the forest paths. Old as the trees. Some say it's the last thing Nyxia made."] },
    },
    signs: { '13,2': () => say(null, 'A small shrine of black stone. A crescent moon is carved into it, and someone has left a fresh candle.') },
  },
  hollowash: {
    name: 'Hollowmere (Ashes)', theme: 'ashen', music: 'sorrow', under: 'h', exitArt: 'path', back: [8, 11], start: [12, 13, 'up'], embers: () => true, tint: 'rgba(60,10,0,0.18)',
    rows: null, // built below from hollowmere
    npcs: {
      1: { look: 'elder', name: 'Elder Moth', talk: [() => "Most of the village fled into the Dreamers' Pass when the fire started. South, through the mountains. Verai knows the way. Go. We will find each other again. Whisperers always do."] },
      2: { look: 'hollowman', name: 'Survivor', talk: [() => "It sang. That golden thing. It sang while everything burned. I'll hear that hymn for the rest of my life."] },
      3: { look: 'oracle', name: 'Oracle Sef', talk: [() => "I told you. A golden woman who does not blink. I hate being right. I hate it so much."] },
    },
    signs: { '13,2': async () => ashShrine() },
  },
  // =========================================================================
  goldengrove: {
    name: 'Goldengrove', theme: 'town', music: 'town2', under: 'g', exitArt: 'path', back: [21, 22], start: [13, 16, 'up'],
    rows: [
      "tttttttttttttttttttttttttttt",
      "tFFFgggRRRRRgggggRRRRRgggFFt",
      "tFFFgggRRRRRgggggRRRRRgggFFt",
      "tfffgggbbWbbgggggbbAbbgggfft",
      "tggggg,,,,,,,,,,,,,,,,,ggggt",
      "tgg1gg,ggggggOOgggggg,gg2ggt",
      "tggggg,ggggggOOgggggg,ggggFt",
      "tgRRRRR,ggggg,,ggggg,RRRRRgt",
      "tgRRRRR,ggggg,,ggggg,RRRRRgt",
      "tgbbNbb,ggg3g,,g4ggg,bbHbbgt",
      "tg,,,,,,,,,,,,,,,,,,,,,,,,gt",
      "tgggg5gggggg,,gggggggg6gggFt",
      "tgffffffgggg,,gggRRRRRggggFt",
      "tgFFFFFFgggg,,gggbbIbbggg7gt",
      "tgFFFFFFgggg,,g,,,,,,,,ggggt",
      "tggggggggggg,,ggggggggggggFt",
      "tggggggggggg,,ggggggggggggFt",
      "ttttttttttttXXtttttttttttttt",
    ],
    shops: 'goldengrove',
    npcs: {
      1: { look: 'halfling', move: 'wander', talk: [() => "Welcome to Goldengrove! Bread, barley, and the best harvest feast this side of the Dawnpeaks. Stay for the pie. Everybody stays for the pie."] },
      2: { look: 'halfling', move: 'wander', talk: [() => "A dragon lady! My gran said dragons eat sheep. I said that's rude to assume. Do you eat sheep?", () => ""] },
      3: { look: 'priest', name: 'Priest', talk: [() => "The Dawnguard came through last week asking about 'Nyxian sympathizers.' I told them the only thing we sympathize with here is a failed pie crust."] },
      4: { look: 'woman', talk: [() => "Brightwater's across the river, east. The Tower of Dawn lighthouse went dark a month ago. Ships have been running aground on the reefs ever since."] },
      5: { look: 'oldman', talk: [() => "You can change your calling any time, you know. Knight in the morning, hymn-singer by supper. The gods don't mind, as long as you mean it."] },
      6: { look: 'halfling', name: 'Bridgewarden Pip', talk: [async () => bridgeEvent()] },
      7: { look: 'child', move: 'wander', talk: [() => "Mister Pip is in charge of the big bridge! He has a lever! I'm not allowed to touch the lever."] },
    },
  },
  // =========================================================================
  brightwater: {
    name: 'Brightwater', theme: 'town', music: 'town', under: 'g', exitArt: 'path', back: [45, 24], start: [2, 9, 'right'],
    rows: [
      "tttttttttttttttttttttttt~~~~~~",
      "tgRRRRRgRRRRRgRRRRRggggs~~~~~~",
      "tgRRRRRgRRRRRgRRRRRggggs~~~~~~",
      "tgbbWbbgbbAbbgbbIbbgggss~~~~~~",
      "tg,,,,,,,,,,,,,,,,,,,,,===~~~~",
      "tggg1gggggggggg2ggggg,g===~~~~",
      "tgRRRRRgggRRRRRgggga,g=====~~~",
      "tgRRRRRgggRRRRRggggg,g===3=~~~",
      "tgbbNbbgggbbHbbggggg,g===~~~~~",
      "X,,,,,,,,,,,,,,,,,,,,,,===~~~~",
      "tgggg4ggggggggg5ggggg,gss~~~~~",
      "tgFFggggggggggggggg6g,gss~~~~~",
      "ttttttttttttttttttttttss~~~~~~",
    ],
    shops: 'brightwater', underAt: { '3': '=' },
    npcs: {
      1: { look: 'sailor', move: 'wander', talk: [() => "Three wrecks on the Harmony reefs this month. Without the Tower of Dawn's light, the sea just eats ships."] },
      2: { look: 'merchant', move: 'wander', talk: [() => "Blackpowder from Kharak Yr! Don't ask how I got it. Don't tell the harbormaster. Actually, buy it from the item shop, it's legal there. Mostly."] },
      3: { look: 'grell', name: 'Harbormaster Grell', talk: [async () => grellEvent()] },
      4: { look: 'woman', talk: [() => "Tidelight Celebration's cancelled this year. Can't float lanterns on the bay if you can't see the bay."] },
      5: { look: 'priest', name: 'Thalaran Priest', talk: [() => "The sea reflects the soul. Respect its bounty and its wrath. The shrine by the pier is open to all."] },
      6: { look: 'dawnguard', name: 'Dawnguard', talk: [() => !flag('chimera') && "Nothing to see at the lighthouse. The High Luminar's own orders. Move along.", () => "I, uh. I'm going to go stand somewhere else now."] },
    },
    signs: { '19,6': async () => thalaraShrine() },
  },
  // =========================================================================
  tower1: {
    name: 'Tower of Dawn - Ground', theme: 'tower', music: 'tower', under: '.', exitArt: 'floor', back: [54, 28], start: [8, 12, 'up'], enc: 'tower', encRate: 0.06, bg: 'tower',
    rows: [
      "#################",
      "#Q..#.......#..>#",
      "#...#.o...o.#...#",
      "#.o.#.......#.o.#",
      "#...##.....##...#",
      "#.......G.......#",
      "#.o...o...o...o.#",
      "#.......L.......#",
      "##..##.....##..##",
      "#...#...o...#...#",
      "#.V.#.......#.Z.#",
      "#...##.....##...#",
      "#...............#",
      "########X########",
    ],
    warps: { '>': { map: 'tower2', at: '<' } },
    chests: { Q: { id: 'c_t1a', item: 'hitonic', n: 2 }, V: { id: 'c_t1b', item: 'ether' }, Z: { id: 'c_t1c', item: 'maskdagger' } },
  },
  tower2: {
    name: 'Tower of Dawn - Lens Stair', theme: 'tower', music: 'tower', under: '.', exitArt: 'floor', start: [15, 1, 'down'], enc: 'tower', encRate: 0.065, bg: 'tower',
    rows: [
      "#################",
      "#>......#......<#",
      "#.####..#..####.#",
      "#.#Q.#..#..#..#.#",
      "#.#..#.....#V.#.#",
      "#.#..###.###..#.#",
      "#.#...........#.#",
      "#.####.o.o.####.#",
      "#.......G.......#",
      "#####..###..#####",
      "#Z..............#",
      "#################",
    ],
    warps: { '<': { map: 'tower1', at: '>' }, '>': { map: 'tower3', at: '<' } },
    chests: { Q: { id: 'c_t2a', item: 'tidecharm' }, V: { id: 'c_t2b', gold: 900 }, Z: { id: 'c_t2c', item: 'sunhelm' } },
  },
  tower3: {
    name: 'Tower of Dawn - Lantern Room', theme: 'tower', music: 'tower', under: '.', exitArt: 'floor', start: [1, 10, 'right'], bg: 'tower',
    rows: [
      "#################",
      "#*.............*#",
      "#......GGG......#",
      "#.....GG1GG.....#",
      "#......GGG......#",
      "#...............#",
      "#..o.........o..#",
      "#...............#",
      "#.......L.......#",
      "#...............#",
      "#<..............#",
      "#################",
    ],
    warps: { '<': { map: 'tower2', at: '>' } }, underAt: { '1': 'G' },
    npcs: {
      1: { img: 'b_chimera', scale: 0.4, name: 'Sunforged Chimera', show: () => !flag('chimera'), talk: [async () => chimeraEvent()] },
    },
    steps: { '8,5': () => !flag('chimera') && chimeraEvent(), '7,5': () => !flag('chimera') && chimeraEvent(), '9,5': () => !flag('chimera') && chimeraEvent() },
  },
  // =========================================================================
  embrace1: {
    name: 'Elaris\'s Embrace', theme: 'vale', music: 'vale', under: 'g', exitArt: 'path', back: [40, 35], start: [12, 13, 'up'], enc: 'embrace', encRate: 0.06, bg: 'vale',
    rows: [
      "KKKKKKKKKKKKKKKKKKKKKKKKKK",
      "KKKKKgggllggK>KgglllggKKKK",
      "KKKglllggggg,,,gggllllgKKK",
      "KKgglggwwwggg,gggwwwglggKK",
      "KgglggwwwwwgKK,KwwwwwgglgK",
      "KgQgggwwwwgKKK,KKwwwwgggVK",
      "KggglgggwggK,,,,KgwgggglgK",
      "KKgggllgggg,,KK,,ggglllgKK",
      "KKKggggg,,,,KKKK,,,,gggKKK",
      "KKKKgglgg,gLgKKgg,ggllgKKK",
      "KKKgglll,,gggggg,,,gggKKKK",
      "KKgglgg,,gglllgggg,,gggKKK",
      "KKggggg,ggKKKKKKgg,,gggZKK",
      "KKKgggg,,,,,,,,,,,,,,ggKKK",
      "KKKKKKKKKKKKXKKKKKKKKKKKKK",
    ],
    warps: { '>': { map: 'embrace2', at: '<' } },
    chests: { Q: { id: 'c_e1a', item: 'hitonic', n: 3 }, V: { id: 'c_e1b', item: 'circlet' }, Z: { id: 'c_e1c', item: 'bellcharm' } },
  },
  embrace2: {
    name: 'Elaris\'s Embrace - Twin Falls', theme: 'vale', music: 'vale', under: 'g', exitArt: 'path', start: [12, 13, 'up'], enc: 'embrace', encRate: 0.05, bg: 'vale',
    rows: [
      "KKKKKKKKKKKKKKKKKKKKKKKKK",
      "KKKKKwwwKKKKKKKKKwwwKKKKK",
      "KKKKwwwwwKKKKKKKwwwwwKKKK",
      "KKKKKwwwwwwwwwwwwwwwKKKKK",
      "KKKlllgwwwwwwwwwwwglllKKK",
      "KKgllggggggg1gggggggllgKK",
      "KKglgggggggggggggggggglKK",
      "KKgggQgggllllllgggggVggKK",
      "KKKggggggglllllgggggggKKK",
      "KKKKgggLggggggggggggKKKKK",
      "KKKKKggggggg,ggggggKKKKKK",
      "KKKKKKKggggg,gggggKKKKKKK",
      "KKKKKKKKKKgg,ggKKKKKKKKKK",
      "KKKKKKKKKKKg<gKKKKKKKKKKK",
      "KKKKKKKKKKKKKKKKKKKKKKKKK",
    ],
    warps: { '<': { map: 'embrace1', at: '>' } },
    chests: { Q: { id: 'c_e2a', item: 'dreamsilk' }, V: { id: 'c_e2b', item: 'blossomstaff' } },
    npcs: {
      1: { img: 'b_bloomcolossus', scale: 0.42, name: 'Bloomheart Colossus', show: () => !flag('colossus'), talk: [async () => colossusEvent()] },
      2: { look: 'vesper', name: 'High Luminar Vesper', show: () => flag('colossus') && !flag('ch1end'), talk: [async () => soniaReveal()] },
    },
    steps: { '12,8': () => !flag('colossus') && colossusEvent(), '11,8': () => !flag('colossus') && colossusEvent(), '13,8': () => !flag('colossus') && colossusEvent() },
  },
};
// The burned village reuses Hollowmere's layout
MAPS.hollowash.rows = MAPS.hollowmere.rows.map(r => r.replace(/[1-7]/g, 'h').replace(/[Rb]/g, 'x').replace(/[gF]/g, 'h').replace(/[IN]/g, 'x').replace(/t/g, 'x').replace(/a/, 'a'));
(() => { // place the survivors
  const put = (x, y, c) => { const r = MAPS.hollowash.rows[y]; MAPS.hollowash.rows[y] = r.slice(0, x) + c + r.slice(x + 1); };
  put(13, 3, 'h'); put(14, 3, '1'); put(6, 7, '2'); put(19, 12, '3');
})();
